### ISSUE TITLE
ImportError: No module named properties.p

### ISSUE THREAD

**Issue by paulmbrantley** [anandjoshi91/pythonpropertyfileloader#1]
ImportError: No module named properties.p

Seem to be missing '__  init __.py' when installing in Windows and Linux using pip, which is causing module not to be found error.
Tested with Python 2.7.10(Linux) and Python 2.7.9. 

P.S.
This looks like extacly what I needed for my project.
Thank You!

**Comment by anandjoshi91** [comment]
Hello,

Thank you for bringing this to my notice   I have updated the project. 

Please install the latest version 2.1
